### ISSUE TITLE
Using an external ZAP

### ISSUE THREAD

**Issue by WPCleaner** [jenkinsci/zap-pipeline-plugin#13]
Hello,

In the [Javadoc of StartZapTest](https://github.com/jenkinsci/zap-pipeline-plugin/blob/master/src/main/java/com/vrondakis/zap/workflow/StartZapStep.java#L23), it says that `if zapHome is not set this will not start ZAP (but still make calls if you're running it locally`, which seems great for using an external ZAP (for example in a separate container).

But since [this modification](https://github.com/jenkinsci/zap-pipeline-plugin/commit/6c00ba672502192c0f5ad8b3acb5194ab9f767ec#diff-ed7d88c7dcd920596277285b40b59770), [StartZapExecution will fail if zapHome is not set](https://github.com/jenkinsci/zap-pipeline-plugin/blob/master/src/main/java/com/vrondakis/zap/workflow/StartZapExecution.java#L54), which is not consistent with the Javadoc of the other class.

Is there any way to use an external ZAP with this plugin?

Thanks,
Nicolas

**Comment by shardy-lbar** [comment]
You can now add "extenalZap: true" option to the startZap step, and it will skip trying to start a local application.

Additionally, add "keepAlive: true" to the archiveZap step, so that it does not send the "shutdown" command to the zap instance.
