### ISSUE TITLE
ArchiveZap doesn't wait for passive scan to finish

### ISSUE THREAD

**Issue by mum-viadee** [jenkinsci/zap-pipeline-plugin#14]
We're using OWASP ZAP to run as passive scanner while running our large automated UI tests suite. Something we noticed is, that the amount of alerts vary a bit even without changes in our application. When we wait some seconds after the UI tests everything works and the number of alerts is constant. 

Although the workaround with the sleep seems to work, the archiveZAP step itself should wait for any passive scan to finish before results are retrieved.

For passive scans there is the method _pscanViewRecordsToScan_ in the ZAP api to query the number of records the passive scanner still has to scan. This could be used in the archiveZAP step easily.

**Comment by TrinuxSG** [comment]
Hi @mum-viadee , I had exactly the same problem... The sleep step help me as well
