### ISSUE TITLE
Add action to configure IDs of the passive rules that will be enabled or disabled

### ISSUE THREAD

**Issue by bhecquet** [jenkinsci/zap-pipeline-plugin#28]
### Feature Request

When doing passive scan, all passive rules are applied, which is not always desirable from a developper point of view.
It should be possible to configure it (it is possible through API (https://www.zaproxy.org/docs/api/?shell#pscanactionenablescanners)

**Comment by shardy-lbar** [comment]
Released as part of v1.13
