### ISSUE TITLE
AllowedHosts : type is not supported

### ISSUE THREAD

**Issue by flocurity** [jenkinsci/zap-pipeline-plugin#5]
Hi,

I'm very new to jenkins pipelines, and I'd like to use zap.

After installing 1.9 version of your plugin (fetched form [mvnrepository](https://mvnrepository.com/artifact/com.vrondakis.zap/zap-pipeline/1.9) ), I tried to create my first stage. But I can't :
- under the property **AllowedHosts** there's the message `This property type is not supported`
- as this property is mandatory, I can't save this stage.

Do I need to install an other dependency ?

FYI:
- my Jenkins is 2.150.3
- BlueOcean Pipeline Editor is 1.14.0

**Comment by vrondakis** [comment]
Can you send the pipeline script you used

**Comment by flocurity** [comment]
I don't have any script, I try to configure via the Blue Ocean UI, and this is my first step. I havan't played with pipelines before.

Ps : How fast :+1:

**Comment by flocurity** [comment]
![2019-04-03_16h15_34](https://user-images.githubusercontent.com/30314113/55485965-c1695900-562b-11e9-924d-aeeddab75e3d.png)

**Comment by vrondakis** [comment]
ZAP scans all the hosts in allowedHosts, but it's optional - if it's not set it will scan just localhost. Not sure why the UI thinks it's required. I've never used the pipeline editor, is there a manual script editor too?

**Comment by flocurity** [comment]
Nope, there's unfortunately no manual script editor.

I'll read on How to script those pipelines (I suppose via Jenkinsfile).

But it would be great if you find how to deal with required/non-required properties in the pipeline editor !

Thanks for your time

**Comment by flocurity** [comment]
Nope, there's unfortunately no manual script editor.

I'll read on How to script those pipelines (I suppose via Jenkinsfile).

But it would be great if you find how to deal with required/non-required properties in the pipeline editor !

Thanks for your time
