### ISSUE TITLE
zapAliveCheck won't work on slaves

### ISSUE THREAD

**Issue by kalioz** [jenkinsci/zap-pipeline-plugin#6]
Hi, iI'm trying to get the plugin working on a kubernetes environement, and the plugin throw the error `zap: Failed to start ZAP on 127.0.0.1:9999. Socket timed out`
After some research, I think that zap is in fact correctly started on the slave but the master is trying to ping itself.

Changing the zapHost wouldn't work in my case as the port won't be reachable from the master (the slave execute both the zaproxy and the test requests)

Is it possible to add an option to either :
1) have the plugin execute the test on the agent (see [this](https://wiki.jenkins.io/display/JENKINS/Making+your+plugin+behave+in+distributed+Jenkins))
2) bypass the alive check (I did not check if the rest of the plugin needs to have access to zap directly)

( for reference, the failing alive check is on [src/main/java/com/vrondakis/zap/ZapDriverImpl.java:386](https://github.com/jenkinsci/zap-pipeline-plugin/blob/master/src/main/java/com/vrondakis/zap/ZapDriverImpl.java#L386) which throw a build error on [src/main/java/com/vrondakis/zap/workflow/StartZapExecution.java:81](https://github.com/jenkinsci/zap-pipeline-plugin/blob/master/src/main/java/com/vrondakis/zap/workflow/StartZapExecution.java#L81))

I'll try to add the option (1) by myself but have never worked with jenkins plugins before.
thanks,

**Comment by vrondakis** [comment]
Hey
The plugin uses ZAP's HTTP API to do things such as starting an attack & fetching report data. You wouldn't be able to just skip the alive check as nothing else would work.

Why would ZAP not be reachable from master (I didn't understand that part)? We have a master-slave setup with ZAP installed on the slave and proxy our tests, which run in a docker container, through it. It sounds like all you need to do is set zapHost to the IP of the slave
