### ISSUE TITLE
False positive file not working

### ISSUE THREAD

**Issue by mum-viadee** [jenkinsci/zap-pipeline-plugin#7]
Hi,

I've created a Jenkins Pipeline to run some automated UI tests and proxy all requests through the zap. Therefore I use this plugin.  To get rid of a few false positives I created a false positive file and placed it in the git repository where the UI tests are keept, too. This repository is checked out at the beginning of every build job. 

 I tried to configure the archiveZAP step with the falsePositivesFilePath as shown in your examples, but it doesn't work. 

After examine the source code I think the plugin looks for the false positive file in the job directory and not in the workspace. These two paths are, at least in our Jenkins installation completely disjoint.  

Where do I have to place the false positive file correctly?  Or is it a bug in ZapArchive.java and the call of the method "saveFalsePositives" must use job.getBuildDir() instead of run.getRootDir()?

**Comment by vrondakis** [comment]
Hi, it does in fact look in the job directory. We have our false positives file committed to our main repository, but I can see your use case. 
I will look into it and change it

**Comment by salslab** [comment]
I added the below to my multibranch pipeline job to workaround this issue:

sh "cp -f zapFalsePositives.json /var/jenkins_home/jobs/MY_JOB_NAME/branches/dev/builds/${currentBuild.number}"

Now I can see zap-false-positives.json in zap directory and also alert-count.json shows falsePositives = 1.
{"highAlerts":0,"mediumAlerts":0,"lowAlerts":0,"falsePositives":1,"buildName":"#150"}

However, the report still displays the alert. Looks like the URI in main.js is not being matched using regex.

Also the build still fails when the alerts are 0. Does failAllAlerts also consider false positives? Or is there another bug which makes the build fail?

**Comment by mum-viadee** [comment]
I'm using a similar workaround. For me it is working. The false positives are not considered in my setup `archiveZap(failHighAlerts: 1, failMediumAlerts: 1, failLowAlerts: 20, falsePositivesFilePath: "**/zapFalsePositives.json")`
I'm only facing the issue, that the false positive supression is not working in the report view. In the statisc graph it is working correctly. I've reported this already in [Issue 9](https://github.com/jenkinsci/zap-pipeline-plugin/issues/9).
